# Mathematical operations take time

In [1]:
import random
import time

n = 100_000

# two lists of n random numbers from 0 to 99
x = [random.randrange(100) for _ in range(n)]
y = [random.randrange(100) for _ in range(n)]

#start counting time
start = time.time()

#make a list by multiplying the elements of the lists
i, z = 0, []
while i < n:
    z.append(x[i] * y[i])
    i += 1
    
#print elapsed time
end = time.time()
end-start

0.0222322940826416

# Can we do it faster?

 for ( int i = 0; i < n; i++) {
  c[i] = a[i] * b[i]; 
 }

* No need to manipulate with Python objects
* losing the benefits of Python (readability, .....................................................................................................................................................)

# Alternative: Numpy

In [2]:
import numpy as np

x = np.array(x)
y = np.array(y)

#start counting time
start = time.time()

#...
z = x * y

#print elapsed time
end = time.time()
end-start

0.001920938491821289

* element-by-element operation is executed by pre-compiled C or Fortrun code
* vectorized code
 * absence of explicit loops and indexing
 * fewer lines and bugs, more resembles mathematical notation
* fundamental package for scientific computing in Python
* scientific and mathematical Python-based packages are using ndarrays from numpy
* convert Python sequences to ndarrays prior to processing
 
 ## ndarray
* n-dimensional arrays of homogeneous data types
* able to create from **list** or tuple
* multidimensional array is created as a sequence of sequences
* dimensions are called axes

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr2d = np.array([[1,2,3],[4,5,6]])
# first axis has 2 elements
# second axis has 3 elements
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

difference between ndarray and standard sequences:
* fixed size at creation
* changes by creating new and deleting original

# ????????????????????????????????????????????????????????????????????????????????????????????/

* same data type  (dtype)

In [5]:
arr = np.array(['s',1])
arr

array(['s', '1'], dtype='<U1')

In [6]:
arr[1]+1          # ...ERROR

TypeError: can only concatenate str (not "int") to str

  *  object as dtype

In [4]:
arr = np.array(['s',[1,2]])
arr

array(['s', list([1, 2])], dtype=object)

* important attributes are: ndim, shape, size, dtype, itemsize, data

In [5]:
arr = np.array([[1,1,1],[2,2,2]])
arr.ndim

2

In [6]:
# when using objects
arr = np.array([[1,1],[1,2,3]])
arr.ndim

1

In [7]:
arr = np.array([[1,1,1],[2,2,2]])
arr.shape   # 2 elements, 3 elements

(2, 3)

In [8]:
arr.size  # total number of elements

6

In [9]:
arr.dtype  # type of element

dtype('int64')

In [16]:
import sys
print(arr.itemsize) # byte size of each element of the array
sys.getsizeof(int()) # why more? reference counter (8) and a pointer to the type (8)

8


24

In [14]:
arr.data

## Basic Operations

In [15]:
arr2d = np.array([[1,2,3,4],[8,9,10,11]])
arr2d+arr2d

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [16]:
arr2d-arr2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
arr2d*arr2d

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [18]:
1/arr2d

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [19]:
arr2d**2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

## Broadcasting
* how numpy treats arrays with different shapes during arithmetic operations

In [20]:
arr = np.arange(6)  # creates an array of integers from 0 to 6
arr.resize((2,3))  # reshapes it into a matrix
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
arr2 = np.array([[0,1,3]])
arr + arr2

array([[0, 2, 5],
       [3, 5, 8]])

* numpy compares the shapes of the two arrays
* two dimensions are compatible when they are equal or one of them is 1

In [22]:
# if not...
arr2 = np.array([[0,1]])
arr + arr2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

## Indexing

In [88]:
def basic_array():
    arr2d = np.zeros((6,6))
    for i in range(6):
        for j in range(6):
            arr2d[i,j] = 10*i+j
    return arr2d

arr2d = basic_array()
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [89]:
arr2d[0][1]

1.0

In [90]:
arr2d[0,1]

1.0

### Indexing - Fancy Indexing

In [179]:
# can use list for indexing
# integers in list do not have to be in order
l1 = [4,2]
arr2d = basic_array()
arr2d[l1]

array([[40., 41., 42., 43., 44., 45.],
       [20., 21., 22., 23., 24., 25.]])

In [180]:
# columns
arr2d[:,l1] = 0
arr2d

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 13.,  0., 15.],
       [20., 21.,  0., 23.,  0., 25.],
       [30., 31.,  0., 33.,  0., 35.],
       [40., 41.,  0., 43.,  0., 45.],
       [50., 51.,  0., 53.,  0., 55.]])

In [181]:
# rows and columns ...ERROR
l2 = [0,1,3]
arr2d[l1, l2]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [182]:
# What happened? Let's try same dimensions
arr2d[[1,2,3],[1,2,3]]

array([11.,  0., 33.])

In [183]:
# We can do this
arr2d[l1][:,l2]

array([[40., 41., 43.],
       [20., 21., 23.]])

In [184]:
# Let's try this
arr2d[l1][:,l2] = 99
arr2d
# ... does not really work

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 13.,  0., 15.],
       [20., 21.,  0., 23.,  0., 25.],
       [30., 31.,  0., 33.,  0., 35.],
       [40., 41.,  0., 43.,  0., 45.],
       [50., 51.,  0., 53.,  0., 55.]])

In [185]:
# this notation
arr2d[l1] = 88
print(arr2d)
print("\n")
# is equal to
arr2d.__setitem__(l1, 77)
print(arr2d)
print("\n--------------------------------------------")
# there is no need to create neither view or copy,
# because the method can be evaluated in place
# meaning, there is NO new object creation involved
# However...
arr2d[l1][:,l2] = 66
print(arr2d)
# this notation is equal to
aux = arr2d.__getitem__(l1)     # creation of new object
aux.T.__setitem__(l2, 55)
print('\n{}\n\n{}'.format(aux, arr2d))

[[ 0.  1.  0.  3.  0.  5.]
 [10. 11.  0. 13.  0. 15.]
 [88. 88. 88. 88. 88. 88.]
 [30. 31.  0. 33.  0. 35.]
 [88. 88. 88. 88. 88. 88.]
 [50. 51.  0. 53.  0. 55.]]


[[ 0.  1.  0.  3.  0.  5.]
 [10. 11.  0. 13.  0. 15.]
 [77. 77. 77. 77. 77. 77.]
 [30. 31.  0. 33.  0. 35.]
 [77. 77. 77. 77. 77. 77.]
 [50. 51.  0. 53.  0. 55.]]

--------------------------------------------
[[ 0.  1.  0.  3.  0.  5.]
 [10. 11.  0. 13.  0. 15.]
 [77. 77. 77. 77. 77. 77.]
 [30. 31.  0. 33.  0. 35.]
 [77. 77. 77. 77. 77. 77.]
 [50. 51.  0. 53.  0. 55.]]

[[55. 55. 77. 55. 77. 77.]
 [55. 55. 77. 55. 77. 77.]]

[[ 0.  1.  0.  3.  0.  5.]
 [10. 11.  0. 13.  0. 15.]
 [77. 77. 77. 77. 77. 77.]
 [30. 31.  0. 33.  0. 35.]
 [77. 77. 77. 77. 77. 77.]
 [50. 51.  0. 53.  0. 55.]]


# View and Copy
* view: different view of the same memory content
* copy: contents are physically stored in another location

In [208]:
# View:
arr = np.arange(6)   # base array
aux = arr.view()     # view
aux[0] = 99
print('changed aux, arr = {}'.format(arr))
arr[1] = 88
print('changed arr, aux = {}'.format(aux))

changed aux, arr = [99  1  2  3  4  5]
changed arr, aux = [99 88  2  3  4  5]


In [209]:
aux.base   # returns None if the array owns the data, otherwise returns the original object

array([99, 88,  2,  3,  4,  5])

#### View - slicing
* special case of view
* similar syntax as with other Python objects

In [211]:
print(arr2d)
arr2d_slice = arr2d[1:3, 3:5]    # base array
arr2d_slice[:] = 99              # view
arr2d

[[ 0.  1.  0.  3.  0.  5.]
 [10. 11.  0. 99. 99. 15.]
 [77. 77. 77. 99. 99. 77.]
 [30. 31.  0. 33.  0. 35.]
 [77. 77. 77. 77. 77. 77.]
 [50. 51.  0. 53.  0. 55.]]


array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 99., 99., 15.],
       [77., 77., 77., 99., 99., 77.],
       [30., 31.,  0., 33.,  0., 35.],
       [77., 77., 77., 77., 77., 77.],
       [50., 51.,  0., 53.,  0., 55.]])

In [189]:
# problems with fancy indexing
arr2d_slice = arr2d[1:3, [2,3]]
arr2d_slice[:] = 77
arr2d

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 99., 99., 15.],
       [77., 77., 77., 99., 99., 77.],
       [30., 31.,  0., 33.,  0., 35.],
       [77., 77., 77., 77., 77., 77.],
       [50., 51.,  0., 53.,  0., 55.]])

#### Copy

In [190]:
arr2d_slice = arr2d[1:3, 3:5].copy()
arr2d_slice[:] = 88
arr2d

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 99., 99., 15.],
       [77., 77., 77., 99., 99., 77.],
       [30., 31.,  0., 33.,  0., 35.],
       [77., 77., 77., 77., 77., 77.],
       [50., 51.,  0., 53.,  0., 55.]])

In [191]:
arr2d_slice   # extra physical copy

array([[88., 88.],
       [88., 88.]])

In [193]:
print(arr2d_slice.base)

None


#### Just for fun, what will work?

In [34]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
l1 = [0,2]

arr2d[:1, :][:, l1] = 99
arr2d

array([[99,  2, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
l1 = [0,2]

arr2d[l1, :][:, :1] = 99
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing - Boolean indexing

In [ ]:
arr = np.array([1,2,3,4,5])
arr < 3

In [36]:
# Can we use two conditions?      ...ERROR
arr < 3 and arr > 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [38]:
# Python cannot override and, or for arrays
(arr < 3) & (arr > 1)

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
(arr < 3) | (arr > 3 )

In [ ]:
# brackets are needed   ...ERROR
arr < 3 | arr > 3

In [ ]:
# modifying
arr[(arr < 3) & (arr > 1)] = 99
arr

## Input and Output
* numpy has its own functions for saving and loading arrays
* .npy file stores all the information required to recontruct an array (data, dtype, shape)
* .npz (zip) stores several arrays

In [ ]:
# saving single array
# creates or overrides the file
np.save('arr',arr2d)
aux = np.load('arr.npy')
aux

In [ ]:
np.save('arr',arr)
aux = np.load('arr.npy')
aux

In [ ]:
# saving multiple arrays
# one default key, one set as we wish
np.savez('ziparr', arr, y = arr2d)   
aux = np.load('ziparr.npz')

# shows files
aux.files

In [ ]:
aux['arr_0']

In [ ]:
aux['y']

In [ ]:
# override
arr = np.array([1,1])
np.savez('ziparr', z = arr)
aux = np.load('ziparr.npz')
aux.files

#### Input and Output 
##### using PyTables
* using HDF5 format, which supports large, complex, heterogenous data
* file directory like structure
 https://stackoverflow.com/questions/30376581/save-numpy-array-in-append-mode/30379177

#### or JSON

....SAMI

# Subclassing
### since the subject is called OOP

* view casting - casting an existing ndarray as a given subclass
* creating new from template

### view casting
* take an ndarray of any subclass and return a view of the array as a specified subclass

In [215]:
class C(np.ndarray):        
    def my_func(self):
        self[0] += 100
arr = np.arange(5)
c_arr = arr.view(C)
print('before: c_arr = {}'.format(c_arr))
c_arr.my_func()
print('after:  c_arr = {}'.format(c_arr))
print('after:  arr   = {}'.format(arr))

before: c_arr = [0 1 2 3 4]
after:  c_arr = [100   1   2   3   4]
after:  arr   = [100   1   2   3   4]


In [216]:
c_arr.base

array([100,   1,   2,   3,   4])

### creating new from template
* numpy finds that it needs to create new instance from a template instance

In [221]:
aux = c_arr[1:]        # aux is a view onto the c_arr data
aux.base               # we get an ndarray of C subclass which points to the data in the original

C([100,   1,   2,   3,   4])

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


https://numpy.org/doc/stable/user/basics.subclassing.html

https://numpy.org/doc/stable/reference/arrays.classes.html

https://numpy.org/doc/stable/user/basics.dispatch.html#basics-dispatch

## Dispatch mechanism
#### Writing custom array containers
* for writing custom N-dimensional array containers that are compatible with numpy API
* recommended approach
* example: CuPy arrays (N-dimensional arrays on GPU)

In [238]:
class mod_eye:
    def __init__(self, N, value):
        self.N = N
        self.value = value
    def __array__(self):
        return self.value * np.eye(5)
arr = mod_eye(5,2)
np.asarray(arr)     # converts the input to an array, calls __array__() if it exists

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [239]:
arr            # does not change arr itself

In [241]:
np.multiply(arr, 5)          # again takes in __array__(), output is standard ndarray

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

In [242]:
type(arr)                  # what if we want this to also return array type?

__main__.mod_eye

# TODO

# C-API
https://numpy.org/doc/stable/user/c-info.html
# TODO

# np.concatenate

In [115]:
np.concatenate([[1], [0,4], 5*[1,2]])

array([1, 0, 4, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

# np.meshgrid
* returns coordinate matrices from coordinate vectors

In [106]:
np.meshgrid([1,2], [1,2,3,4,5])

[array([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]),
 array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])]

# np.mgrid
* returns mesh-grid ndarrays all of the same dimensions
* if the step length is a complex number, for example 2j, then 2 specifies the number of points between the start and stop value (stop value included)

In [56]:
aux = np.mgrid[0:4, 0:5:3j]
aux

array([[[0. , 0. , 0. ],
        [1. , 1. , 1. ],
        [2. , 2. , 2. ],
        [3. , 3. , 3. ]],

       [[0. , 2.5, 5. ],
        [0. , 2.5, 5. ],
        [0. , 2.5, 5. ],
        [0. , 2.5, 5. ]]])

In [9]:
np.mgrid[0:3]

array([0, 1, 2])

# np.ogrid
* returns an open (not fleshed out) multi-dimensional "meshgrid"    ????? it is a list
* only one dimension of each returned array is greater than 1
* dimension and number of the output arrays are equal to the number of indexing dimensions

In [52]:
aux = np.ogrid[0:4, 0:5:3j]
aux

[array([[0.],
        [1.],
        [2.],
        [3.]]),
 array([[0. , 2.5, 5. ]])]

In [53]:
print(aux[0].shape)
aux[0].ndim

(4, 1)


2

In [54]:
print(aux[1].shape)
aux[1].ndim

(1, 3)


2

# np.r_
* translates slice objects to concatenation along the first axis

In [ ]:
aux = np.r_[np.array([1,8,3]), 9, [7, 6]]
aux

* we can specify the axis using string integers

In [79]:
arr = np.array([[1,2,3], [4,5,6]])
aux = np.r_['0', arr, arr] # concatenate along the first axis
aux

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
aux = np.r_['-1', arr, arr] # concatenate along the last axis
aux

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [90]:
aux = np.r_['1,3', arr, arr]  # concatenate along the first axis, dim >= 3
aux

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [96]:
aux = np.r_['r', arr, arr]   # r or c creates matrix
aux

matrix([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

# np.c_
* translates slice objects to concatenation along the second axis

In [97]:
np.c_[arr, arr]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [103]:
aux = np.c_[np.array([[1,8,3]]), 9, [[7, 6]]]            # not the same as the first one
aux

array([[1, 8, 3, 9, 7, 6]])

# np.vectorize
* defince a vectorized function
 *  input: a nested sequence of objects or ndarrays
 *  output: single ndarray or a tuple of ndarrays

In [159]:
def my_func(a, b):
    return a+b
aux = np.vectorize(my_func)
aux(a=[1,2,3,4], b=3)

array([4, 5, 6, 7])

In [160]:
# can exclude from vectorization
def my_func(a, b):
    aux = list(b)
    res = aux.pop(0)
    while aux:
        res += a + aux.pop(0)
    return res
aux = np.vectorize(my_func, excluded=['b'])
aux(a=[1,2,3,4], b=[3,2,1])

array([ 8, 10, 12, 14])