In [2]:
import random
import time
import sys

n = 100_000

# two lists of n random numbers from 0 to 99
x = [random.randrange(100) for _ in range(n)]
y = [random.randrange(100) for _ in range(n)]

#start counting time
start = time.time()

#make a list by multiplying the elements of the lists
i, z = 0, []
while i < n:
    z.append(x[i] * y[i])
    i += 1
    
#print elapsed time and memory
end = time.time()
mem = sys.getsizeof(z)
print('elapsed time = {}\nused memoty = {}'.format(end-start, mem))

elapsed time = 0.028583526611328125
used memoty = 824456


## Jak zrychlit?

C++
* není zapotřebí manipulovat s Pytnovskými objekty

## Alternativa: Numpy

In [3]:
import numpy as np

x = np.array(x)
y = np.array(y)

#start counting time
start_alt = time.time()

#...
z = x * y

#print elapsed time
end_alt = time.time()
mem_alt = sys.getsizeof(z)
print('elapsed time = {}\nused memoty = {}'.format(end_alt-start_alt, mem_alt))

elapsed time = 0.002123117446899414
used memoty = 800096


In [4]:
 (end-start) - (end_alt-start_alt)

0.02646040916442871

In [5]:
mem - mem_alt

24360

# NumPy
* základní balíček pro vědecké výpočty v Pythonu
* operace mezi prvky jsou provedeny v překompilovaném C nebo Fortrunu
* vektorizovaný kód
 * "zmizel" nám for loop
 * méně řádků = méně bugů
 
 ## ndarray
* n-rozměrné homogenní pole
* můžeme vytvořit z **listu** nebo tuplu
* vícerozměré pole je vytvořeno jako sekvence ze sekvencí

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

* rozdíl mezi ndarray a std. sekvencemi:
 * homogenní
 * pevná velikost

* same data type  (dtype)

In [8]:
arr = np.array(['s',1])
arr

array(['s', '1'], dtype='<U1')

In [9]:
arr[1]+1          # ...ERROR

TypeError: can only concatenate str (not "int") to str

   *  objekt jako dtype

In [10]:
arr = np.array(['s',[1,2]])
arr

array(['s', list([1, 2])], dtype=object)

### důležité attributy: 

* ndim

In [11]:
arr = np.array([[1,1,1],[2,2,2]])
arr.ndim

2

při použití objeků...

In [12]:
arr = np.array([[1,1],[1,2,3]])
arr.ndim

1

* tvar (shape)

In [13]:
arr = np.array([[1,1,1],[2,2,2]])
arr.shape

(2, 3)

* velikost (size)

In [14]:
arr.size

6

* typ dat (dtype)

In [15]:
arr.dtype

dtype('int64')

* veklikost prvku (itemsize)

In [16]:
print(arr.itemsize)
sys.getsizeof(int())

8


24

* data

In [17]:
arr.data

## Základní operace

In [18]:
arr2d = np.array([[1,2,3,4],[8,9,10,11]])
arr2d+arr2d

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [19]:
arr2d-arr2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
arr2d*arr2d

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [21]:
1/arr2d

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [22]:
arr2d**2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

## Broadcasting
* aneb když máme 2 pole o jiných rozměrech

In [23]:
arr = np.arange(6)  # creates an array of integers from 0 to 6
arr.resize((2,3))  # reshapes it into a matrix
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr2 = np.array([[0,1,3]])
arr + arr2

array([[0, 2, 5],
       [3, 5, 8]])

* NumPy porovná the shapes of the two arrays
* 2 dimenze jsou kompatibilní, pokud jsou stejné nebo jedna z nich je rovna 1

In [25]:
# if not...
arr2 = np.array([[0,1]])
arr + arr2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

## Indexování

In [26]:
def basic_array():
    arr2d = np.zeros((6,6))
    for i in range(6):
        for j in range(6):
            arr2d[i,j] = 10*i+j
    return arr2d

arr2d = basic_array()
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [27]:
arr2d[0][1]

1.0

In [28]:
arr2d[0,1]

1.0

### Indexování - Fancy Indexing
* lze použít list intů jako index
* inty nemusí být seřazené

In [29]:
l1 = [4,2]
arr2d = basic_array()
arr2d[l1]

array([[40., 41., 42., 43., 44., 45.],
       [20., 21., 22., 23., 24., 25.]])

In [30]:
arr2d[:,l1] = 0
arr2d

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 13.,  0., 15.],
       [20., 21.,  0., 23.,  0., 25.],
       [30., 31.,  0., 33.,  0., 35.],
       [40., 41.,  0., 43.,  0., 45.],
       [50., 51.,  0., 53.,  0., 55.]])

In [31]:
# ...ERROR
l2 = [0,1,3]
arr2d[l1, l2]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

Co se stalo?

In [32]:
arr2d[[1,2,3],[1,2,3]]

array([11.,  0., 33.])

Můžeme provést toto

In [33]:
arr2d[l1][:,l2]

array([[40., 41., 43.],
       [20., 21., 23.]])

ale potom nefunguje přiřazování

In [34]:
arr2d[l1][:,l2] = 99
arr2d

array([[ 0.,  1.,  0.,  3.,  0.,  5.],
       [10., 11.,  0., 13.,  0., 15.],
       [20., 21.,  0., 23.,  0., 25.],
       [30., 31.,  0., 33.,  0., 35.],
       [40., 41.,  0., 43.,  0., 45.],
       [50., 51.,  0., 53.,  0., 55.]])

Co se tady děje...

In [35]:
arr2d = basic_array()
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [36]:
#this notation
arr2d[l1] = 100
print(arr2d)
print("\n")
# is equal to
arr2d.__setitem__(l1, 0)
print(arr2d)

[[  0.   1.   2.   3.   4.   5.]
 [ 10.  11.  12.  13.  14.  15.]
 [100. 100. 100. 100. 100. 100.]
 [ 30.  31.  32.  33.  34.  35.]
 [100. 100. 100. 100. 100. 100.]
 [ 50.  51.  52.  53.  54.  55.]]


[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [ 0.  0.  0.  0.  0.  0.]
 [30. 31. 32. 33. 34. 35.]
 [ 0.  0.  0.  0.  0.  0.]
 [50. 51. 52. 53. 54. 55.]]


* není zapotřebí vytvořit view nebo copy (více dále)
* tzn, nevytváří se žádný nový objekt

In [37]:
arr2d = basic_array()
# However...
arr2d[l1][:,l2] = 100
# this notation is equal to
aux = arr2d.__getitem__(l1)     # creation of new object
aux.T.__setitem__(l2, 0)
print('\naux = \n{}\n\narr2d =\n{}'.format(aux, arr2d))


aux = 
[[ 0.  0. 42.  0. 44. 45.]
 [ 0.  0. 22.  0. 24. 25.]]

arr2d =
[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]
 [30. 31. 32. 33. 34. 35.]
 [40. 41. 42. 43. 44. 45.]
 [50. 51. 52. 53. 54. 55.]]


## View and Copy
* view: nový pohled na ten samý úsek paměti
* copy: kopie paměti v jiné lokaci


### View

In [38]:
arr = np.arange(5)   # base array
aux = arr.view()     # view
aux[0] = 100
arr[1] = 200
print('arr = {}'.format(arr))
print('aux = {}'.format(aux))

arr = [100 200   2   3   4]
aux = [100 200   2   3   4]


.base vrací None, pokud pole data vlastní, jinak vrací původní objekt

In [39]:
aux.base

array([100, 200,   2,   3,   4])

* stejný výsledek mohu získat jako

In [40]:
arr = np.arange(5)
aux = arr
aux[0] = 100
arr[1] = 200
print('arr = {}'.format(arr))
print('aux = {}'.format(aux))

arr = [100 200   2   3   4]
aux = [100 200   2   3   4]


* stačí =
* co se děje?
 * pokud zavřeme obě oči (src jsem nestudoval): překlad do C++ v souboru view.cpp
* jaký je tedy smysl .view()?      ... view casting (uvedeme za chvíli)

#### View - slicing
* speciální případ View
* obdobná syntaxe jako u jiných Pytnovských objektů

In [41]:
arr2d = basic_array()
arr2d_slice = arr2d[1:3, 3:5]    # base array
arr2d_slice[:] = 100              # view
arr2d

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [ 10.,  11.,  12., 100., 100.,  15.],
       [ 20.,  21.,  22., 100., 100.,  25.],
       [ 30.,  31.,  32.,  33.,  34.,  35.],
       [ 40.,  41.,  42.,  43.,  44.,  45.],
       [ 50.,  51.,  52.,  53.,  54.,  55.]])

* problémy pokud kombinujeme slicing a fancy indexing

In [42]:
arr2d_slice = arr2d[1:3, [2,3]]
arr2d_slice[:] = 77
arr2d

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [ 10.,  11.,  12., 100., 100.,  15.],
       [ 20.,  21.,  22., 100., 100.,  25.],
       [ 30.,  31.,  32.,  33.,  34.,  35.],
       [ 40.,  41.,  42.,  43.,  44.,  45.],
       [ 50.,  51.,  52.,  53.,  54.,  55.]])

#### Copy

In [43]:
arr2d = basic_array()
arr2d_slice = arr2d[1:3, 3:5].copy()
arr2d_slice[:] = 100
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [44]:
arr2d_slice

array([[100., 100.],
       [100., 100.]])

In [45]:
print(arr2d_slice.base)

None


#### Která úprava změní původní pole?

In [46]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
l1 = [0,2]

arr2d[:1, :][:, l1] = 100
arr2d

array([[100,   2, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [47]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
l1 = [0,2]

arr2d[l1, :][:, :1] = 100
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexování - Boolean indexing

In [48]:
arr = np.array([1,2,3,4,5])
arr < 3

array([ True,  True, False, False, False])

* lze použít 2 podmínky, tak jak normálně v Pythonu?

In [49]:
arr < 3 and arr > 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

* musíme použít značení v C++ (ale NEZDVOJUJEME) + závorky

In [50]:
(arr < 3) & (arr > 1)

array([False,  True, False, False, False])

In [51]:
(arr < 3) | (arr > 3 )

array([ True,  True, False,  True,  True])

In [52]:
arr < 3 | arr > 3

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

* indexování

In [53]:
arr[(arr < 3) & (arr > 1)] = 99
arr

array([ 1, 99,  3,  4,  5])

## Subclassing
* view casting - vytvoří pohled na existující pole jako specializovanou podtřídu
* Dispatch mechanism - tvorba vlastních kontainerů polí
### view casting

In [54]:
class C(np.ndarray):        
    def my_func(self):
        self[0] += 100
arr = np.arange(5)
c_arr = arr.view(C)
print('before: c_arr = {}'.format(c_arr))
c_arr.my_func()
print('after:  c_arr = {}'.format(c_arr))
print('after:  arr   = {}'.format(arr))

before: c_arr = [0 1 2 3 4]
after:  c_arr = [100   1   2   3   4]
after:  arr   = [100   1   2   3   4]


In [55]:
c_arr.base

array([100,   1,   2,   3,   4])

* nestačí to jenom přetypovat?

In [56]:
aux = C(arr)
aux

C([[[[[4.04738577e-320, 1.81816158e-321, 0.00000000e+000,
       2.56691688e-316],
      [4.94065646e-324, 2.56692953e-316, 4.94065646e-324,
       2.56691846e-316],
      [1.18575755e-322, 6.91623619e-310, 6.91622088e-310,
       1.06099790e-313]],

     [[4.94065646e-324, 6.36598737e-314, 6.36598738e-314,
       6.91623640e-310],
      [6.91622088e-310, 2.12199579e-313, 1.27319747e-313,
       1.48539705e-313],
      [4.94065646e-324, 2.56692399e-316, 1.18575755e-322,
       6.91623611e-310]]]],



   [[[[4.94065646e-324, 1.18575755e-322, 1.69759663e-313,
       2.33419537e-313],
      [0.00000000e+000, 0.00000000e+000, 2.33419537e-313,
       2.56692083e-316],
      [2.56692320e-316, 2.56692636e-316, 1.27319747e-313,
       2.54639495e-313]],

     [[2.54639495e-313, 2.56691767e-316, 2.56692715e-316,
       0.00000000e+000],
      [0.00000000e+000, 8.06358401e-313, 0.00000000e+000,
       4.94065646e-324],
      [2.54639495e-313, 0.00000000e+000, 0.00000000e+000,
       6.91622088e-

### Dispatch mechanism
* doporučený přístup
* př: CuPy arrays (n-rozměrná pole na GPU)
* užití \_\_array__()

In [57]:
class Diagonal:
    def __init__(self, N, value):
        self.N = N
        self.value = value
    def __array__(self):
        return self.value * np.eye(5)
arr = Diagonal(5,2)
np.asarray(arr)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [58]:
arr = np.multiply(arr, 5)
arr

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

In [59]:
type(arr)

numpy.ndarray

## Input & Output
* NumPy má vlastní funkce pro zápis a načítání polí
* komprese
* vytvoří nebo přepíše
* .npy uloží všechny potřebné informace potřebné k rekonstrukci pole (data, dtype, shape)

In [60]:
arr2d = basic_array()
np.save('arr2d',arr2d)
aux = np.load('arr2d.npy')
aux

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [61]:
arr2d += 100
np.save('arr2d',arr2d)
aux = np.load('arr2d.npy')
aux

array([[100., 101., 102., 103., 104., 105.],
       [110., 111., 112., 113., 114., 115.],
       [120., 121., 122., 123., 124., 125.],
       [130., 131., 132., 133., 134., 135.],
       [140., 141., 142., 143., 144., 145.],
       [150., 151., 152., 153., 154., 155.]])

* .npz (zip) uloží více polí
 * klíč

In [62]:
arr = np.array([1,2,3])
np.savez('ziparr', arr, y = arr2d)   
aux = np.load('ziparr.npz')

aux.files

['y', 'arr_0']

In [63]:
aux['arr_0']

array([1, 2, 3])

In [64]:
aux['y']

array([[100., 101., 102., 103., 104., 105.],
       [110., 111., 112., 113., 114., 115.],
       [120., 121., 122., 123., 124., 125.],
       [130., 131., 132., 133., 134., 135.],
       [140., 141., 142., 143., 144., 145.],
       [150., 151., 152., 153., 154., 155.]])

In [65]:
arr = np.array([1,1])
np.savez('ziparr', z = arr)
aux = np.load('ziparr.npz')
aux.files

['z']

## RNG
* pseudo náhodná čísla
* dříve RandomState
* BitGenerátory vytvoří posloupnosti náhodných čísel
* Generátory transofrmují tyto posloupnosti do posloupností, které se řídí určitým rozdělením
 * Generátory mohou být inicializovány pomocí více BitGenerátorů

In [79]:
from numpy import random as ran 

In [80]:
rng = ran.default_rng()     # new instance of Generator
vals1 = rng.standard_normal(10)
vals1

array([-0.3885631 , -0.74722904, -0.09739062, -0.16593073,  1.08539259,
       -1.18788393, -0.85973722, -0.4984932 ,  1.11156485, -0.00743973])

In [81]:
vals2 = rng.standard_normal(10)
vals2

array([-0.27471504,  0.16653337,  2.69032377,  0.05558164, -0.90107646,
       -1.5102952 , -1.36387026, -0.77405891, -0.1565701 ,  0.6365117 ])

  * Generátor obsahuje svůj vlastní interní BitGenerátor

In [82]:
rng.bit_generator

### Seeding
...zhruba
* chceme reprodukovatelnou posloupnost náhodných čísel
* BitGenerator si vezme libovolně velké přirozené číslo, nebo list takových čísel jako seed
 * problém s kvalitou, tj: chceme kvalitní výstup náhodných čísel bez ohledu na seed
 * delegováno funkci SeedSequence

In [83]:
seed = 123456789
ss = ran.SeedSequence(seed)
rng = ran.default_rng(ss)
vals1 = rng.standard_normal(10)
vals1

array([-0.23632286,  0.54671636,  0.10037845,  1.67662222,  0.49484456,
        1.14633764,  1.7473833 ,  0.12327598, -0.34086587,  0.1500319 ])

In [84]:
rng = ran.default_rng(ss)
vals2 = rng.standard_normal(10)
vals2

array([-0.23632286,  0.54671636,  0.10037845,  1.67662222,  0.49484456,
        1.14633764,  1.7473833 ,  0.12327598, -0.34086587,  0.1500319 ])

In [85]:
vals1 - vals2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
vals3 = rng.standard_normal(10)
vals3

array([ 0.84465446,  0.90357677, -0.28058986, -0.98720833,  1.02633847,
       -1.04710489,  2.80647303,  2.32627448,  1.21538563,  0.32935954])

In [87]:
vals1 - vals3

array([-1.08097732, -0.35686042,  0.38096831,  2.66383055, -0.53149391,
        2.19344254, -1.05908973, -2.2029985 , -1.5562515 , -0.17932764])

#### Entropie
* atribut SeedSequence
* (berte s rezervou stackoverflow -> moje hlava -> čeština -> sem) náhodné číslo, které získá OS. Toto číslo se může například brát z pohybu myši.

In [88]:
ss = np.random.SeedSequence()
ss.entropy

258663423566849372213627733824984335059

* obvyklý postup generace náhodných čísel

In [89]:
ss_aux = np.random.SeedSequence()
ss = np.random.SeedSequence(ss_aux.entropy)
rng = ran.default_rng(ss)
vals = rng.standard_normal(10)
vals

array([ 0.27599487, -1.07430023, -0.44339105,  0.5554872 , -0.91681312,
       -0.22808996, -1.32851405, -0.56707583,  1.52380778, -0.20590259])

## Lineární algebra
### linalg
* překryv s scipy.linalg
* SciPy obsahuje víc funkcí, např. LU rozklad
* některé funkce se liší v argumentech, např: sc.linalg.eig, np.linalg.solve

In [108]:
from scipy import linalg

In [100]:
arr1 = np.array([0,1,2,3,4])
arr2 = np.array([5,6,7,8,9])

In [101]:
np.inner(arr1, arr2)

80

In [102]:
np.outer(arr1, arr2)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

In [103]:
arr2d = basic_array()
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

### vlastní čísla

In [104]:
arr2d = np.diag([1,2,3])
np.linalg.eig(arr2d)

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [105]:
arr2d = np.array([[1, -1], [1, 1]])
np.linalg.eig(arr2d)

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

* zaokrouhlovací chyby

In [106]:
arr2d = np.array([[1 + 1e-9, 0], [0, 1 - 1e-9]])
np.linalg.eig(arr2d)

(array([1., 1.]),
 array([[1., 0.],
        [0., 1.]]))

##### SciPy

In [118]:
arr2d = np.diag([1,2,3])
linalg.eig(arr2d)

(array([1.+0.j, 2.+0.j, 3.+0.j]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

* SciPy umožňuje modifikovat matici $\mathbb{B}$ ve vztahu $\mathbb{A} - \lambda\mathbb{B}$
 * defaultně $\mathbb{B} = \mathbb{I}$

In [119]:
arr2d2 = 2*np.eye(3)
linalg.eig(arr2d, arr2d2)

(array([0.5+0.j, 1. +0.j, 1.5+0.j]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

#### QR algoritmus

In [120]:
q, r = np.linalg.qr(arr2d)

In [121]:
q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
r

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

### LAR

In [154]:
arr2d = np.diag([1,2,3])
b = [1,1,1]
np.linalg.solve(arr2d, b)

array([1.        , 0.5       , 0.33333333])

In [155]:
arr2d2 = np.stack([arr2d, arr2d])
b2 = np.stack([b, b])

In [156]:
np.linalg.solve(arr2d2, b2)

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

##### SciPy

In [158]:
arr2d = np.diag([1,2,3])
b = [1,1,1]
linalg.solve(arr2d, b)

array([1.        , 0.5       , 0.33333333])

In [159]:
arr2d2 = np.stack([arr2d, arr2d])
b2 = np.stack([b, b])

In [160]:
linalg.solve(arr2d2, b2)

ValueError: Input a needs to be a square matrix.

#### inverzní matice

In [162]:
np.linalg.inv(arr2d)

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

## další

#### np.concatenate

In [ ]:
np.concatenate([[1], [0,4], 5*[1,2]])

# np.meshgrid
* returns coordinate matrices from coordinate vectors

In [ ]:
np.meshgrid([1,2], [1,2,3,4,5])

# np.mgrid
* returns mesh-grid ndarrays all of the same dimensions
* if the step length is a complex number, for example 2j, then 2 specifies the number of points between the start and stop value (stop value included)

In [ ]:
aux = np.mgrid[0:4, 0:5:3j]
aux

In [ ]:
np.mgrid[0:3]

# np.ogrid
* returns an open (not fleshed out) multi-dimensional "meshgrid"    ????? it is a list
* only one dimension of each returned array is greater than 1
* dimension and number of the output arrays are equal to the number of indexing dimensions

In [ ]:
aux = np.ogrid[0:4, 0:5:3j]
aux

In [ ]:
print(aux[0].shape)
aux[0].ndim

In [ ]:
print(aux[1].shape)
aux[1].ndim

# np.r_
* translates slice objects to concatenation along the first axis

In [ ]:
aux = np.r_[np.array([1,8,3]), 9, [7, 6]]
aux

* we can specify the axis using string integers

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
aux = np.r_['0', arr, arr] # concatenate along the first axis
aux

In [ ]:
aux = np.r_['-1', arr, arr] # concatenate along the last axis
aux

In [ ]:
aux = np.r_['1,3', arr, arr]  # concatenate along the first axis, dim >= 3
aux

In [ ]:
aux = np.r_['r', arr, arr]   # r or c creates matrix
aux

# np.c_
* translates slice objects to concatenation along the second axis

In [ ]:
np.c_[arr, arr]

In [ ]:
aux = np.c_[np.array([[1,8,3]]), 9, [[7, 6]]]            # not the same as the first one
aux

# np.vectorize
* defince a vectorized function
 *  input: a nested sequence of objects or ndarrays
 *  output: single ndarray or a tuple of ndarrays

In [ ]:
def my_func(a, b):
    return a+b
aux = np.vectorize(my_func)
aux(a=[1,2,3,4], b=3)

In [ ]:
# can exclude from vectorization
def my_func(a, b):
    aux = list(b)
    res = aux.pop(0)
    while aux:
        res += a + aux.pop(0)
    return res
aux = np.vectorize(my_func, excluded=['b'])
aux(a=[1,2,3,4], b=[3,2,1])